# Generated by Django 5.2.10 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Caption or description for the featured image', max_length=500),
        ),
    ]
