# Generated by Django 5.2.10 on 2026-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_researchproject_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='hover_image',
            field=models.ImageField(blank=True, help_text='High-res fieldwork image shown on hover', null=True, upload_to='projects/hover/'),
        ),
    ]
