# Generated by Django 5.2.10 on 2026-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_researchproject_hover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='info_description',
            field=models.TextField(blank=True, verbose_name='Info Description'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long Description'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
