# Generated by Django 5.2.11 on 2026-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_researchproject_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
