# Generated by Django 5.2.11 on 2026-02-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_researchproject_start_date'),
        ('team', '0007_alter_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='collaborators',
            field=models.TextField(blank=True, help_text='Names of investigators/collaborators from CSV', verbose_name='Other Officers / Collaborators'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='financial_outlay',
            field=models.CharField(blank=True, max_length=100, verbose_name='Financial Outlay'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='research_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field of Research'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='co_investigators',
            field=models.ManyToManyField(blank=True, related_name='projects_as_co_pi', to='team.teammember', verbose_name='Co-Investigators (Lab Members)'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=300, verbose_name='Funding Agency'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_pi', to='team.teammember', verbose_name='Principal Investigator (Lab Member)'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Project Title (Topic)'),
        ),
    ]
