# Generated by Django 5.2.11 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_researchproject_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='grant_amount',
            field=models.CharField(blank=True, help_text='Specific grant amount (e.g., ₹6.75 L, USD 10,300)', max_length=100, verbose_name='Grant / Outlay Amount'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='partner_institutions',
            field=models.TextField(blank=True, help_text='Collaborating organizations (e.g., GMDA, TARU, World Bank)', verbose_name='Partner Institutions'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='project_type',
            field=models.CharField(choices=[('research', 'Research Project'), ('consultancy', 'Consultancy Project')], default='research', max_length=20, verbose_name='Project Type'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='role',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator (PI)'), ('co-pi', 'Co-Principal Investigator (Co-PI)'), ('team_member', 'Project Team Member')], help_text='Role in this project (PI, Co-PI, or Team Member)', max_length=20, verbose_name='Your Role'),
        ),
    ]
