# Generated by Django 5.2.11 on 2026-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_researchproject_grant_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='co_investigators',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='financial_outlay',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='hover_image',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='info_description',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='principal_investigator',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='research_field',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='collaborators',
            field=models.TextField(blank=True, help_text='Names of principal investigators and collaborators', verbose_name='PI / Collaborators'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='description',
            field=models.TextField(help_text='Full project description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=300, verbose_name='Funding Agency / Scheme'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='grant_amount',
            field=models.CharField(blank=True, help_text='e.g., ₹6.75 L, USD 10,300', max_length=100, verbose_name='Grant / Outlay Amount'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this project on the public website', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='role',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator (PI)'), ('co-pi', 'Co-Principal Investigator (Co-PI)'), ('team_member', 'Project Team Member')], help_text='Your role in this project', max_length=20, verbose_name='Your Role'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planned', 'Planned')], default='ongoing', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Project Title'),
        ),
    ]
