# Generated by Django 5.2.11 on 2026-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_researchproject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional: Direct link to project website (overrides detail page)', verbose_name='External Project URL'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the project card', null=True, upload_to='projects/images/', verbose_name='Project Image'),
        ),
    ]
