# Generated by Django 5.2.11 on 2026-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_researchproject_external_link_researchproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planned', 'Upcoming')], default='ongoing', max_length=20, verbose_name='Status'),
        ),
    ]
