# Generated by Django 5.2.10 on 2026-03-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_researchproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='collaborators',
            field=models.TextField(blank=True, help_text='Names of principal investigators and collaborators', null=True, verbose_name='PI / Collaborators'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='external_link',
            field=models.URLField(blank=True, help_text='Optional: Direct link to project website (overrides detail page)', null=True, verbose_name='External Project URL'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Funding Agency / Scheme'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='grant_amount',
            field=models.CharField(blank=True, help_text='e.g., ₹6.75 L, USD 10,300', max_length=100, null=True, verbose_name='Grant / Outlay Amount'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='partner_institutions',
            field=models.TextField(blank=True, help_text='Collaborating organizations (e.g., GMDA, TARU, World Bank)', null=True, verbose_name='Partner Institutions'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='role',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator (PI)'), ('co-pi', 'Co-Principal Investigator (Co-PI)'), ('team_member', 'Project Team Member')], help_text='Your role in this project', max_length=20, null=True, verbose_name='Your Role'),
        ),
    ]
