# Generated by Django 5.2.10 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text="e.g., 'Global Temperature Anomaly', 'CO2 Concentration'", max_length=200)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current metric value', max_digits=10)),
                ('unit', models.CharField(help_text="e.g., '°C', 'ppm', '%'", max_length=50)),
                ('trend', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief explanation of the metric')),
                ('source', models.CharField(help_text="Data source name (e.g., 'NOAA', 'NASA')", max_length=300)),
                ('source_url', models.URLField(blank=True, help_text='Link to data source')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order on homepage (lower numbers first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show this metric on homepage widget')),
            ],
            options={
                'verbose_name': 'Climate Metric',
                'verbose_name_plural': 'Climate Metrics',
                'ordering': ['display_order', 'metric_name'],
            },
        ),
    ]
