# Generated by Django 5.2.10 on 2026-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_climatemetrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateMetrics',
        ),
    ]
