# Generated by Django 5.2.11 on 2026-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_climatemetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Research Notice',
                'verbose_name_plural': 'Research Notices',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology Notice',
                'verbose_name_plural': 'Technology Notices',
                'ordering': ['-event_date'],
            },
        ),
    ]
