# Generated by Django 5.2.11 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_researchnotice_technologynotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Short description of the tutorial')),
                ('external_link', models.URLField(help_text='YouTube link or external website URL')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('topic', models.CharField(choices=[('data-analysis', 'Data Analysis'), ('gis', 'GIS & Mapping'), ('modeling', 'Modeling'), ('programming', 'Programming'), ('climate-science', 'Climate Science'), ('statistics', 'Statistics'), ('visualization', 'Visualization'), ('other', 'Other')], default='other', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Auto-extracted for YouTube, or manual URL')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'ordering': ['order', '-created_date'],
            },
        ),
    ]
