# Generated by Django 5.2.11 on 2026-02-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='topic',
        ),
    ]
