# Generated by Django 5.2.11 on 2026-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tutorial_description_remove_tutorial_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='is_playlist',
            field=models.BooleanField(default=False, help_text="True if this is the main playlist video, False if it's a lecture"),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='lecture_number',
            field=models.IntegerField(blank=True, help_text='Order of lecture within playlist (1, 2, 3...)', null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='playlist_id',
            field=models.CharField(blank=True, help_text="ID to group videos into a playlist (e.g., 'urban-ecosystem')", max_length=100, null=True),
        ),
    ]
