# Generated by Django 5.2.11 on 2026-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tutorial_is_playlist_tutorial_lecture_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagestats',
            name='years_of_research',
            field=models.IntegerField(default=15),
        ),
    ]
