# Generated by Django 5.2.11 on 2026-02-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. Urban Climate, Vernacular Arch.', max_length=100)),
                ('description', models.TextField()),
                ('impact_metrics', models.CharField(help_text='e.g. -2°C Temp Reduction, 30% Energy Savings', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='impact/stories/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2023 or 2021-22', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('organization', models.CharField(help_text='e.g. MoHUA, Govt. of India', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ResearchHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('globe', 'Globe/Earth'), ('trending', 'Trending/Growth'), ('award', 'Award/Badge'), ('check', 'Checkmark/Success')], default='globe', max_length=20)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Link to learn more')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
