# Generated by Django 5.2.11 on 2026-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_impactstory_policyimpact_researchhighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnotice',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the notice card', null=True, upload_to='research_tech/'),
        ),
        migrations.AddField(
            model_name='technologynotice',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the notice card', null=True, upload_to='research_tech/'),
        ),
    ]
