# Generated by Django 5.2.11 on 2026-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_researchnotice_image_technologynotice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('Research', 'Research Focus'), ('Technology', 'Technology Used')], default='Research', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField(help_text='Date for the notice (Initiated/Adoption date)')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Image for the notice card', null=True, upload_to='research_tech/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Research & Tech Notice',
                'verbose_name_plural': 'Research & Tech Notices',
                'ordering': ['-event_date'],
            },
        ),
        migrations.DeleteModel(
            name='ResearchNotice',
        ),
        migrations.DeleteModel(
            name='TechnologyNotice',
        ),
    ]
