# Generated by Django 5.2.10 on 2026-04-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rtnotice_delete_researchnotice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactstory',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Urban Climate, Vernacular Arch.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='impactstory',
            name='impact_metrics',
            field=models.CharField(blank=True, help_text='e.g. -2°C Temp Reduction, 30% Energy Savings', max_length=200, null=True),
        ),
    ]
