# Generated by Django 5.2.10 on 2026-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='research_interests',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='google_scholar_url',
            field=models.URLField(blank=True, verbose_name='Google Scholar URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
    ]
