# Generated by Django 5.2.10 on 2026-02-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_teammember_bio_remove_teammember_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='e.g., Professor, PhD Student, Research Associate', max_length=100),
        ),
    ]
