# Generated by Django 5.2.10 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator'), ('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('postdoc', 'Post-Doctoral Researcher'), ('phd', 'PhD Scholar'), ('mtech', 'M.Tech Student'), ('research_associate', 'Research Associate'), ('visiting', 'Visiting Researcher'), ('alumni', 'Alumni')], help_text='Formal designation/title', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma-separated research areas (e.g., Climate Modeling, Urban Heat Islands)'),
        ),
    ]
