# Generated by Django 5.2.10 on 2026-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammember_designation_teammember_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='focus_area',
            field=models.CharField(blank=True, help_text='Primary research focus (shown on hover)', max_length=200),
        ),
    ]
