# Generated by Django 5.2.10 on 2026-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_focus_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='focus_area',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='research_interests',
        ),
    ]
