# Generated by Django 5.2.10 on 2026-02-02 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Workshop/Notice',
                'verbose_name_plural': 'Workshops/Notices',
                'ordering': ['-event_date'],
            },
        ),
    ]
