"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from botocore.config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-fallback-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()
]

# CSRF Trusted Origins - Required for Django 4.0+ when behind a proxy/different domain
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "import_export",
    "simple_history",
    "crispy_forms",
    "crispy_bootstrap5",
    "storages",
    # Custom apps
    "core",
    "team",
    "projects",
    "publications",
    "workshops",
    "contact",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "core.middleware.session_security.DashboardSecurityMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Uses PostgreSQL on Railway (via DATABASE_URL), SQLite locally

DATABASES = {
    "default": dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# Supabase Storage (S3-compatible)
# ---------------------------------------------------------------------------
AWS_S3_ENDPOINT_URL = os.getenv("SUPABASE_S3_ENDPOINT", "").strip()
AWS_S3_REGION_NAME = os.getenv("SUPABASE_S3_REGION", "").strip()
AWS_S3_ACCESS_KEY_ID = os.getenv("SUPABASE_S3_ACCESS_KEY", "").strip()
AWS_S3_SECRET_ACCESS_KEY = os.getenv("SUPABASE_S3_SECRET_KEY", "").strip()
AWS_STORAGE_BUCKET_NAME = os.getenv("SUPABASE_BUCKET", "media").strip()

# AWS settings for django-storages
AWS_S3_SECURE_URLS = True
AWS_QUERYSTRING_AUTH = False  # Set to True if the bucket is private
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path" # CRITICAL for Supabase S3
AWS_S3_CHECKSUM_MODE = "DISABLED"

# Generate Supabase public URL domain
if AWS_S3_ENDPOINT_URL:
    _parsed = urllib.parse.urlparse(AWS_S3_ENDPOINT_URL)
    _project_id = _parsed.netloc.split('.')[0]
    AWS_S3_CUSTOM_DOMAIN = f"{_project_id}.supabase.co/storage/v1/object/public"
else:
    AWS_S3_CUSTOM_DOMAIN = None


use_supabase = bool(
    AWS_S3_ENDPOINT_URL
    and AWS_S3_ACCESS_KEY_ID
    and AWS_S3_SECRET_ACCESS_KEY
)

if use_supabase:
    STORAGES = {
        "default": {
            "BACKEND": "core.storage.SupabaseMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development or mis‑configured deployment: local disk for media, Whitenoise for static
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Import Export Settings
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ============================================
# EMAIL CONFIGURATION - Gmail SMTP Relay
# ============================================
# NOTE: Using Gmail SMTP because Zimbra (mail.iitr.ac.in) is unreachable off-campus.
# Emails will send via Gmail but FROM field shows official lab email.

# Email Backend (SMTP enabled for real delivery)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Gmail SMTP Configuration (Works from anywhere)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Gmail Credentials
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Sender and Admin Emails (Official lab email)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", "Climatology Lab <climatologylab@ar.iitr.ac.in>"
)
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "climatologylab@ar.iitr.ac.in")

# Email Timeout
EMAIL_TIMEOUT = 30

# ============================================
# AUTHENTICATION CONFIGURATION
# ============================================
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "core:home"

# Session Security Settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Logout when browser window closes
SESSION_COOKIE_AGE = 3600  # 1-hour global session
SESSION_TIMEOUT_DASHBOARD = 60  # 1-minute dashboard inactivity timeout
SESSION_SAVE_EVERY_REQUEST = True  # Reset the timers on every page load/click
