"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-fallback-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()
]

# CSRF Trusted Origins - Required for Django 4.0+ when behind a proxy/different domain
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "import_export",
    "simple_history",
    "crispy_forms",
    "crispy_bootstrap5",
    "cloudinary",
    # Custom apps
    "core",
    "team",
    "projects",
    "publications",
    "workshops",
    "contact",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "core.middleware.session_security.DashboardSecurityMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Uses PostgreSQL on Railway (via DATABASE_URL), SQLite locally

DATABASES = {
    "default": dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# Cloudinary — two ways to configure (CLOUDINARY_URL takes priority):
#
#   Option A (recommended — copy from Cloudinary dashboard):
#     CLOUDINARY_URL = cloudinary://API_KEY:API_SECRET@CLOUD_NAME
#
#   Option B (individual vars):
#     CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET
# ---------------------------------------------------------------------------
_cloudinary_url = os.getenv("CLOUDINARY_URL", "")

if _cloudinary_url and _cloudinary_url.startswith("cloudinary://"):
    # Parse the URL: cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    _url_body = _cloudinary_url[len("cloudinary://"):]          # API_KEY:API_SECRET@CLOUD_NAME
    _at_idx = _url_body.rfind("@")
    cloud_name = _url_body[_at_idx + 1:] if _at_idx != -1 else ""
    _user_info = _url_body[:_at_idx] if _at_idx != -1 else ""
    _colon_idx = _user_info.find(":")
    cloud_key = _user_info[:_colon_idx] if _colon_idx != -1 else _user_info
    cloud_secret = _user_info[_colon_idx + 1:] if _colon_idx != -1 else ""
else:
    # Fall back to individual env vars
    cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME", "").strip()
    cloud_key = os.getenv("CLOUDINARY_API_KEY", "").strip()
    cloud_secret = os.getenv("CLOUDINARY_API_SECRET", "").strip()

# IMPORTANT: strip any accidental whitespace from all values before storing.
# django-cloudinary-storage reads CLOUDINARY_STORAGE in AppConfig.ready() —
# whatever is in this dict is what gets used for signatures.
cloud_name = cloud_name.strip()
cloud_key = cloud_key.strip()
cloud_secret = cloud_secret.strip()

# Populate CLOUDINARY_STORAGE (kept for any legacy references)
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": cloud_name,
    "API_KEY": cloud_key,
    "API_SECRET": cloud_secret,
}

use_cloudinary = bool(cloud_name and cloud_key and cloud_secret)

if use_cloudinary:
    # Use our custom storage backend that calls cloudinary SDK directly.
    # The cloudinary SDK reads CLOUDINARY_URL from the environment automatically —
    # no manual cloudinary.config() call needed.
    STORAGES = {
        "default": {
            "BACKEND": "core.storage.CloudinaryMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development or mis‑configured deployment: local disk for media, Whitenoise for static
    if cloud_name and not (cloud_key and cloud_secret):
        # warn developers/admins when the cloud name was set but other
        # credentials are missing; prevents silent failure
        import warnings

        warnings.warn(
            "CLOUDINARY_CLOUD_NAME is set but API_KEY/API_SECRET are missing; "
            "falling back to FileSystemStorage.",
            RuntimeWarning,
        )

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Import Export Settings
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ============================================
# EMAIL CONFIGURATION - Gmail SMTP Relay
# ============================================
# NOTE: Using Gmail SMTP because Zimbra (mail.iitr.ac.in) is unreachable off-campus.
# Emails will send via Gmail but FROM field shows official lab email.

# Email Backend (SMTP enabled for real delivery)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Gmail SMTP Configuration (Works from anywhere)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Gmail Credentials
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Sender and Admin Emails (Official lab email)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", "Climatology Lab <climatologylab@ar.iitr.ac.in>"
)
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "climatologylab@ar.iitr.ac.in")

# Email Timeout
EMAIL_TIMEOUT = 30

# ============================================
# AUTHENTICATION CONFIGURATION
# ============================================
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "dashboard:home"
LOGOUT_REDIRECT_URL = "core:home"

# Session Security Settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Logout when browser window closes
SESSION_COOKIE_AGE = 3600  # 1-hour global session
SESSION_TIMEOUT_DASHBOARD = 60  # 1-minute dashboard inactivity timeout
SESSION_SAVE_EVERY_REQUEST = True  # Reset the timers on every page load/click
