# Generated by Django 5.2.10 on 2026-02-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(help_text='Comma-separated list of authors', max_length=1000)),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(blank=True, help_text='Journal or Conference name', max_length=300)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book Chapter'), ('thesis', 'Thesis'), ('report', 'Technical Report')], default='journal', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('external_link', models.URLField(blank=True, help_text='External publication link')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
            },
        ),
    ]
