# Generated by Django 5.2.10 on 2026-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex_snippet',
            field=models.TextField(blank=True, help_text='BibTeX citation for this publication', verbose_name='BibTeX Citation'),
        ),
    ]
