# Generated by Django 5.2.10 on 2026-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_bibtex_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='bibtex_snippet',
        ),
    ]
