# Generated by Django 5.2.11 on 2026-02-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_researchproject_start_date'),
        ('publications', '0003_remove_publication_bibtex_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.TextField(blank=True, help_text='Full citation/source text (DATA column)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='publications', to='projects.researchproject'),
        ),
    ]
