# Generated by Django 5.2.11 on 2026-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_citation_publication_related_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
            ],
            options={
                'verbose_name': 'Book Chapter',
                'verbose_name_plural': 'Book Chapters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
            ],
            options={
                'verbose_name': 'Conference Paper',
                'verbose_name_plural': 'Conference Papers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
            ],
            options={
                'verbose_name': 'Guideline',
                'verbose_name_plural': 'Guidelines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
            ],
            options={
                'verbose_name': 'Journal Article',
                'verbose_name_plural': 'Journal Articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Other Document',
                'verbose_name_plural': 'Other Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publications.publication',),
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Publication', 'verbose_name_plural': 'All Publications'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, help_text='Comma-separated list of authors', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book Chapter'), ('thesis', 'Thesis'), ('report', 'Technical Report'), ('guideline', 'Guideline'), ('other', 'Other Document')], default='journal', max_length=50),
        ),
    ]
