# Generated by Django 5.2.11 on 2026-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_book_conference_guideline_journal_otherdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for card display', null=True, upload_to='publications/covers/'),
        ),
    ]
