# Generated by Django 5.2.11 on 2026-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='csv_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CSV ID'),
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_list',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
