# Generated by Django 5.2.11 on 2026-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_publication_created_date_publication_csv_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='conference_type',
            field=models.CharField(blank=True, choices=[('national', 'National Conference'), ('international', 'International Conference')], help_text='Only applicable for Conference Papers', max_length=50, null=True, verbose_name='Conference Type'),
        ),
    ]
