# Generated by Django 5.2.11 on 2026-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_conference_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='conference_type',
        ),
        migrations.AddField(
            model_name='publication',
            name='scope',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International')], help_text='Scope of the conference (National/International)', max_length=20, null=True),
        ),
    ]
