# Generated by Django 5.2.10 on 2026-03-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_remove_publication_conference_type_publication_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideline',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book Chapter'), ('thesis', 'Thesis'), ('report', 'Technical Report'), ('guideline', 'Book'), ('other', 'Other Document')], default='journal', max_length=50),
        ),
    ]
